### ISSUE TITLE
[BUG] App not able to start

### ISSUE THREAD

**Issue by aeris** [DanielScholte/GuildWars2Companion#77]
**Describe the bug**
At start, app crash complaining about missing `libflutter.so`

**To Reproduce**
1. Install app from play store (currently v1.5.7)
2. Start the app
3. App crash

**Expected behavior**
App starts correctly

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7
 - OS: LineageOS 18.1
 - Version 1.5.7

**Additional context**

```
08-10 14:17:42.464 15750 15750 E FlutterLoader: Flutter initialization failed.
08-10 14:17:42.464 15750 15750 E FlutterLoader: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.util.concurrent.FutureTask.report(FutureTask.java:123)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.util.concurrent.FutureTask.get(FutureTask.java:193)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(Unknown Source:23)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:204)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:16)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(Unknown Source:110)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:7)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:15)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.Activity.performCreate(Activity.java:7994)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.Activity.performCreate(Activity.java:7978)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.os.Handler.dispatchMessage(Handler.java:106)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.os.Looper.loop(Looper.java:223)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at android.app.ActivityThread.main(ActivityThread.java:7664)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.lang.reflect.Method.invoke(Native Method)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-10 14:17:42.464 15750 15750 E FlutterLoader: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.lang.System.loadLibrary(System.java:1664)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(Unknown Source:14)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(Unknown Source:0)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-10 14:17:42.464 15750 15750 E FlutterLoader:         at java.lang.Thread.run(Thread.java:923)
08-10 14:17:42.465 15750 15750 D AndroidRuntime: Shutting down VM
08-10 14:17:42.465 15750 15750 E AndroidRuntime: FATAL EXCEPTION: main
08-10 14:17:42.465 15750 15750 E AndroidRuntime: Process: com.danielscholte.guildwars2_companion, PID: 15750
08-10 14:17:42.465 15750 15750 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.danielscholte.guildwars2_companion/com.danielscholte.guildwars2_companion.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-10 14:17:42.465 15750 15750 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(Unknown Source:367)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:204)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:16)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(Unknown Source:110)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:7)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:15)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7994)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7978)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        ... 11 more
08-10 14:17:42.465 15750 15750 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(Unknown Source:23)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        ... 20 more
08-10 14:17:42.465 15750 15750 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(Unknown Source:14)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(Unknown Source:0)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-10 14:17:42.465 15750 15750 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
```

**Comment by aeris** [comment]
Seems v1.5.6 is ok :thinking:

**Comment by DanielScholte** [comment]
That's odd... There shouldn't have been any changes in 1.5.7 to cause that.  
It might be a build error. In which case, i'm planning on releasing an update sometime this week. That might fix it. If it doesn't, please let me know!

**Comment by aeris** [comment]
Hum after some tests, seems 1.5.7 ok too but only when installed from ADB after APK pure download :thinking: 

```
$ unzip GW2\ Companion\ The\ unofficial\ Guild\ Wars\ 2\ App_v1.5.7_apkpure.com.xapk
$ adb install-multiple com.danielscholte.guildwars2_companion.apk config.fr.apk config.arm64_v8a.apk config.xxhdpi.apk
```

And 1.5.7 starts correctly
